version: '3.8'

services:
    postgres-frontend:
        image: postgres:16-alpine
        container_name: nextjs_auth_db
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pku26
            POSTGRES_DB: postgres-frontend
        ports:
            - '5432:5432'
        volumes:
            - postgres_auth_data:/var/lib/postgresql/data

volumes:
    postgres_auth_data:
