version: '3.8'

services:
    postgres-frontend:
        image: postgres:16-alpine
        container_name: nextjs_auth_db
        restart: always
        env_file:
            - ./frontend/.env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - postgres_auth_data:/var/lib/postgresql/data

volumes:
    postgres_auth_data:
